<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>.\srxd-dir-win\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>.\srxd-dir-win\spinrhythm_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>.\srxd-dir-win\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Harmony">
      <HintPath>.\srxd-dir-win\BepInEx\core\BepInEx.Harmony.dll</HintPath>
    </Reference>
    <Reference Include="ChartHelper.Parsing">
      <HintPath>.\srxd-dir-win\BepInEx\plugins\ChartHelper.Parsing.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>.\srxd-dir-win\BepInEx\plugins\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="SpinCore">
      <HintPath>.\srxd-dir-win\BepInEx\plugins\SpinCore.dll</HintPath>
    </Reference>
    <Reference Include="SSD.Game">
      <HintPath>.\srxd-dir-win\spinrhythm_Data\Managed\SSD.Game.dll</HintPath>
    </Reference>
    <Reference Include="SSD.PlayerServiceManager">
      <HintPath>.\srxd-dir-win\spinrhythm_Data\Managed\SSD.PlayerServiceManager.dll</HintPath>
    </Reference>  
    <Reference Include="SSD.Types">
      <HintPath>.\srxd-dir-win\spinrhythm_Data\Managed\SSD.Types.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>.\srxd-dir-win\spinrhythm_Data\Managed\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>.\srxd-dir-win\spinrhythm_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>.\srxd-dir-win\spinrhythm_Data\Managed\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>.\srxd-dir-win\spinrhythm_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>.\srxd-dir-win\spinrhythm_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>.\srxd-dir-win\spinrhythm_Data\Managed\UnityEngine.UI.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\icon.png" />
    <EmbeddedResource Include="Resources\icon.png" />
    <None Remove="Resources\keys.json" />
    <EmbeddedResource Include="Resources\keys.json" />
  </ItemGroup>

  <Target Name="PostBuildScript" AfterTargets="AfterBuild">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder=".\srxd-dir-win\BepInEx\plugins" SkipUnchangedFiles="false" OverwriteReadOnlyFiles="true" />
  </Target>

  <!-- NOTE: Project Name MUST MATCH GENERATED PDB NAME for this rule to pass. -->
  <Target Name="CopyPdbFile" AfterTargets="AfterBuild" Condition="'$(Configuration)' == 'Debug' And '$(OS)' == 'Unix'">
    <Copy SourceFiles="$(TargetDir)\$(ProjectName).pdb" DestinationFolder=".\srxd-dir-win\BepInEx\plugins" SkipUnchangedFiles="false" OverwriteReadOnlyFiles="true" />
  </Target>

</Project>
